MAX_PLOTS_PER_ROW = 5
COLOR_MAJORITY = 'tab:blue'
COLOR_MINORITY = 'tab:orange'
COLOR_MIXED = 'tab:green'
COLOR_BLACK = 'black'
INACTIVE_COLOR = 'lightgrey'
RANKING_LABEL = 'rank k'
INEQUITY_AXIS_LABEL = 'f$_m$ in top-k'
INEQUALITY_AXIS_LABEL = 'Gini in top-k'
DPI = 300
DEFAULT_CELL_SIZE = 3
DEFAULT_FIGSIZE = (10, 5)
MINORITY_CURVE = ['get_fraction_of_minority']
