import numpy as np

EPSILON = 0.00001
EMPTY = [None, np.nan]
MAX_TRIES_EDGE = 100

NO_HOMOPHILY = [0.5, None, np.nan]
NO_TRIADIC_CLOSURE = [0, None, np.nan]

MINORITY_LABEL = 'm'
MAJORITY_LABEL = 'M'

H_MODEL_NAME = 'Homophily'

PA_MODEL_NAME = 'PA'
PAH_MODEL_NAME = 'PAH'
PATC_MODEL_NAME = 'PATC'
PATCH_MODEL_NAME = 'PATCH'

DH_MODEL_NAME = 'DH'
DPA_MODEL_NAME = 'DPA'
DPAH_MODEL_NAME = 'DPAH'

HOMOPHILY_MODELS = [PAH_MODEL_NAME, PATCH_MODEL_NAME, DPAH_MODEL_NAME, H_MODEL_NAME]
