import numpy as np

EPSILON = 0.00001
EMPTY = [None, np.nan]

NO_HOMOPHILY = [0.5, None, np.nan]
NO_TRIADIC_CLOSURE = [0, None, np.nan]

MINORITY_LABEL = 'm'
MAJORITY_LABEL = 'M'

PA_MODEL_NAME = 'PA'
PAH_MODEL_NAME = 'PAH'
PATC_MODEL_NAME = 'PATC'
PATCH_MODEL_NAME = 'PATCH'
HOMOPHILY_MODELS = [PAH_MODEL_NAME, PATCH_MODEL_NAME]