name: Documentation
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx
      - name: Install netin
        run: |
          pip install ./
      - name: Sphinx build
        run: |
          sphinx-build docs/source/ docs/build/html/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/docs' }}
        with:
          publish_branch: documentation
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html/
         
